### ISSUE TITLE
Roadmap📍

### ISSUE THREAD

**Issue by v4l3rio** [pikalab-unibo-students/master-thesis-dizio-ay2324#6]
This issue will define the library roadmap.
The issue will be updated as it is updated with new goals.

**Generic Tasks**
- [ ] Update credentials to allow deployment to test-pypi;
- [ ] Develop examples in jupyter-notebook and related tests for each feature;
- [ ] Add documentation of features already created

**Dataset**
- [ ] Add functionality to pandas dataframe for ease of use 

**Metrics**
- [ ] Statistical Parity Difference
- [ ] Disparate Impact
- [ ] Equal Opportunity Difference
- [ ] Average Absolute Odds Difference

**Pre-Processing**
- [ ] Disparate Impact Remover
- [ ] LFR
- [ ] Optim Preprocessing
- [ ] Reweighing

**In-Processing**
- [ ] Adversarial Debiasing
- [ ] Prejudice Remover
- [ ] Meta-Fair Classifier

**Post-Processing**
- [ ] Equalized Odds
- [ ] Calibrated Equalized Odds
- [ ] Reject Option Classification

**Extra**
- [ ] Provide the basic api for the implementation of FAUCI
